export const USERS_DATA_FETCH_SUCCESS = "USERS_DATA_FETCH_SUCCESS";
export const USERS_DATA_FETCH_FAIL = "USERS_DATA_FETCH_FAIL";

export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const ADD_USER_LOADING = "ADD_USER_LOADING";
